CREATE TABLE [dbo].[Paciente] (
    [Dni]                     INT            IDENTITY (1, 1) NOT NULL,
    [Nombre]                  VARCHAR (50)   NULL,
    [Apellido]                VARCHAR (50)   NULL,
    [FechaIngreso]            DATE           NULL,
    [FechaNacimiento]         DATE           NULL,
    [Edad]                    INT            NULL,
    [Estado]                  VARCHAR (20)   NULL,
    [Peso]                    DECIMAL (5, 2) NULL,
    [Altura]                  DECIMAL (5, 2) NULL,
    [Sexo]                    INT            NULL,
    [Telefono]                VARCHAR (20)   NULL,
    [Email]                   VARCHAR (50)   NULL,
    [idObraSocial]            INT            NOT NULL,
    [idImagen]                INT            NOT NULL,
    [idUbicacion]             INT            NOT NULL,
    [idInformacionAdicional]  INT            NOT NULL,
    [idEnfermedadHereditaria] INT            NOT NULL,
    [idAntecedeToco]          INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([Dni] ASC),
    FOREIGN KEY ([idImagen]) REFERENCES [dbo].[ImagenPaciente] ([idImagen]),
    FOREIGN KEY ([idInformacionAdicional]) REFERENCES [dbo].[InformacionAdicional] ([idInformacionAdicional]),
    FOREIGN KEY ([idObraSocial]) REFERENCES [dbo].[ObraSocial] ([idObraSocial]),
    FOREIGN KEY ([idUbicacion]) REFERENCES [dbo].[Ubicacion] ([idUbicacion]),
    FOREIGN KEY ([Sexo]) REFERENCES [dbo].[Sexo] ([idSexo])
);

